### ISSUE TITLE
JOSS Review: Documentation 

### ISSUE THREAD

**Issue by erexer** [NERDSITU/superblockify#87]
This is part of your [JOSS review ](https://github.com/openjournals/joss-reviews/issues/6798).

Documentation
- [x] “A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?” Can you add to the statement of need to specify who the target audience is. 
- [x] Might be good to clarify that the `data/` dir will be created when the example is run (not required for JOSS acceptance).
- [x] I'm not finding a `Contribute` section in the docs. If it's already in there, can you point me towards it, and if not, can you add a `Contribute` section with instructions on how to 1) Contribute to the software, 2) Report issues or problems with the software, and 3) Seek support.

**Comment by cbueth** [comment]
Thank you for your feedback. We have made and [deployed](https://superblockify.city/) the following changes based on your suggestions:

- a3998ff Thanks for the reminder. We have added a section with a shortened version of the Stetement of Need from the `paper.md`.

- 6a4cc74 We have added a note in the `examples/00-mwe.*` script and notebook to clarify that the `data/` directory will be automatically created when the examples are run.

- 1aa799e We have added a Contribute section in the documentation with a link to the `CONTRIBUTING.md`.

We hope these changes address your concerns. Please let us know if there's anything else we can improve.

**Comment by erexer** [comment]
Great! In the [`Contributing.md`](https://github.com/NERDSITU/superblockify/blob/main/CONTRIBUTING.md#suggesting-enhancements) file, the Table of Contents lists some sections that don't exist, can you remove those. 

Do you welcome PR's from folks? If you do, I'd recommend adding that to the [`Contributing.md`](https://github.com/NERDSITU/superblockify/blob/main/CONTRIBUTING.md#suggesting-enhancements) file (not required for JOSS acceptance).

**Comment by cbueth** [comment]
Great suggestion, just added it in 2b083ad with some further instructions.

**Comment by erexer** [comment]
Awesome!
