### ISSUE TITLE
How can solve: AttributeError: module 'osmnx' has no attribute 'project_gdf'

### ISSUE THREAD

**Issue by SaraHishamBr** [NERDSITU/superblockify#99]
![Capture](https://github.com/user-attachments/assets/25a7fe39-840d-4b92-82fe-b32e7b9bf6aa)

AttributeError                            Traceback (most recent call last)
[<ipython-input-3-c703ac43c5b4>](https://localhost:8080/#) in <cell line: 1>()
----> 1 part = sb.ResidentialPartitioner(
      2     name="Scheveningen_test", city_name="Scheveningen", search_str="Scheveningen, NL",
      3     unit="time",  # "time", "distance", any other edge attribute, or None to count edges
      4 )

2 frames
[/usr/local/lib/python3.10/dist-packages/superblockify/utils.py](https://localhost:8080/#) in load_graph_from_place(save_as, search_string, add_population, only_cache, max_nodes, **gfp_kwargs)
    128     # make shapely.geometry.MultiPolygon from all polygons
    129     # Project to WGS84 to query OSM
--> 130     mult_polygon = ox.project_gdf(mult_polygon, to_crs="epsg:4326")
    131     logger.debug("Reprojected boundary to WGS84 - Downloading graph")
    132     # Get graph - automatically adds distances before simplifying

AttributeError: module 'osmnx' has no attribute 'project_gdf'

**Comment by SaraHishamBr** [comment]
Thank you for your response. Looking forward to the update .

**Comment by cbueth** [comment]
The fix and some further changes have been implemented and the new [`v1.0.1` uploaded to PyPI](https://pypi.org/project/superblockify/). Assuming you are using conda to manage your environment, the package will be automatically updated on conda-forge channel in the next 24h. See its status on the [superblockify-feedstock](https://github.com/conda-forge/superblockify-feedstock/).

Then, you need to update the `superblockify` dependency to fix your issue, eg `conda update superblockify` in your activated environment. Let us know how it goes.

**Comment by cbueth** [comment]
The package is now available on the conda-forge channel: https://anaconda.org/conda-forge/superblockify
